// Copyright ©2017 Simonray (http://github.com/simonray). All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System.ComponentModel.DataAnnotations;

namespace ExchangeRate
{
    /// <summary>
    /// Representation of ISO 4217 currency codes. Generated by XRunner on 01/04/2017.
    /// </summary>
    /// <remarks>
    /// Source: https://en.wikipedia.org/wiki/ISO_4217
    /// </remarks>
    public enum Iso4217
    {
        /// <summary>
        /// AED United Arab Emirates Dirham (784)
        /// </summary>
        [Display(Name = "United Arab Emirates Dirham")]
        AED = 784,
        /// <summary>
        /// AFN Afghan Afghani (971)
        /// </summary>
        [Display(Name = "Afghan Afghani")]
        AFN = 971,
        /// <summary>
        /// ALL Albanian Lek (008)
        /// </summary>
        [Display(Name = "Albanian Lek")]
        ALL = 008,
        /// <summary>
        /// AMD Armenian Dram (051)
        /// </summary>
        [Display(Name = "Armenian Dram")]
        AMD = 051,
        /// <summary>
        /// ANG Netherlands Antillean Guilder (532)
        /// </summary>
        [Display(Name = "Netherlands Antillean Guilder")]
        ANG = 532,
        /// <summary>
        /// AOA Angolan Kwanza (973)
        /// </summary>
        [Display(Name = "Angolan Kwanza")]
        AOA = 973,
        /// <summary>
        /// ARS Argentine Peso (032)
        /// </summary>
        [Display(Name = "Argentine Peso")]
        ARS = 032,
        /// <summary>
        /// AUD Australian Dollar (036)
        /// </summary>
        [Display(Name = "Australian Dollar")]
        AUD = 036,
        /// <summary>
        /// AWG Aruban Florin (533)
        /// </summary>
        [Display(Name = "Aruban Florin")]
        AWG = 533,
        /// <summary>
        /// AZN Azerbaijani Manat (944)
        /// </summary>
        [Display(Name = "Azerbaijani Manat")]
        AZN = 944,
        /// <summary>
        /// BAM Bosnia And Herzegovina Convertible Mark (977)
        /// </summary>
        [Display(Name = "Bosnia And Herzegovina Convertible Mark")]
        BAM = 977,
        /// <summary>
        /// BBD Barbados Dollar (052)
        /// </summary>
        [Display(Name = "Barbados Dollar")]
        BBD = 052,
        /// <summary>
        /// BDT Bangladeshi Taka (050)
        /// </summary>
        [Display(Name = "Bangladeshi Taka")]
        BDT = 050,
        /// <summary>
        /// BGN Bulgarian Lev (975)
        /// </summary>
        [Display(Name = "Bulgarian Lev")]
        BGN = 975,
        /// <summary>
        /// BHD Bahraini Dinar (048)
        /// </summary>
        [Display(Name = "Bahraini Dinar")]
        BHD = 048,
        /// <summary>
        /// BIF Burundian Franc (108)
        /// </summary>
        [Display(Name = "Burundian Franc")]
        BIF = 108,
        /// <summary>
        /// BMD Bermudian Dollar (060)
        /// </summary>
        [Display(Name = "Bermudian Dollar")]
        BMD = 060,
        /// <summary>
        /// BND Brunei Dollar (096)
        /// </summary>
        [Display(Name = "Brunei Dollar")]
        BND = 096,
        /// <summary>
        /// BOB Boliviano (068)
        /// </summary>
        [Display(Name = "Boliviano")]
        BOB = 068,
        /// <summary>
        /// BOV Bolivian Mvdol (funds Code) (984)
        /// </summary>
        [Display(Name = "Bolivian Mvdol (funds Code)")]
        BOV = 984,
        /// <summary>
        /// BRL Brazilian Real (986)
        /// </summary>
        [Display(Name = "Brazilian Real")]
        BRL = 986,
        /// <summary>
        /// BSD Bahamian Dollar (044)
        /// </summary>
        [Display(Name = "Bahamian Dollar")]
        BSD = 044,
        /// <summary>
        /// BTN Bhutanese Ngultrum (064)
        /// </summary>
        [Display(Name = "Bhutanese Ngultrum")]
        BTN = 064,
        /// <summary>
        /// BWP Botswana Pula (072)
        /// </summary>
        [Display(Name = "Botswana Pula")]
        BWP = 072,
        /// <summary>
        /// BYN New Belarusian Ruble (933)
        /// </summary>
        [Display(Name = "New Belarusian Ruble")]
        BYN = 933,
        /// <summary>
        /// BYR Belarusian Ruble (974)
        /// </summary>
        [Display(Name = "Belarusian Ruble")]
        BYR = 974,
        /// <summary>
        /// BZD Belize Dollar (084)
        /// </summary>
        [Display(Name = "Belize Dollar")]
        BZD = 084,
        /// <summary>
        /// CAD Canadian Dollar (124)
        /// </summary>
        [Display(Name = "Canadian Dollar")]
        CAD = 124,
        /// <summary>
        /// CDF Congolese Franc (976)
        /// </summary>
        [Display(Name = "Congolese Franc")]
        CDF = 976,
        /// <summary>
        /// CHE Wir (947)
        /// </summary>
        [Display(Name = "Wir")]
        CHE = 947,
        /// <summary>
        /// CHF Swiss Franc (756)
        /// </summary>
        [Display(Name = "Swiss Franc")]
        CHF = 756,
        /// <summary>
        /// CHW Wir (948)
        /// </summary>
        [Display(Name = "Wir")]
        CHW = 948,
        /// <summary>
        /// CLF Unidad De Fomento (990)
        /// </summary>
        [Display(Name = "Unidad De Fomento")]
        CLF = 990,
        /// <summary>
        /// CLP Chilean Peso (152)
        /// </summary>
        [Display(Name = "Chilean Peso")]
        CLP = 152,
        /// <summary>
        /// CNY Chinese Yuan (156)
        /// </summary>
        [Display(Name = "Chinese Yuan")]
        CNY = 156,
        /// <summary>
        /// COP Colombian Peso (170)
        /// </summary>
        [Display(Name = "Colombian Peso")]
        COP = 170,
        /// <summary>
        /// COU Unidad De Valor Real (uvr) (funds Code) (970)
        /// </summary>
        [Display(Name = "Unidad De Valor Real (uvr) (funds Code)")]
        COU = 970,
        /// <summary>
        /// CRC Costa Rican Colon (188)
        /// </summary>
        [Display(Name = "Costa Rican Colon")]
        CRC = 188,
        /// <summary>
        /// CUC Cuban Convertible Peso (931)
        /// </summary>
        [Display(Name = "Cuban Convertible Peso")]
        CUC = 931,
        /// <summary>
        /// CUP Cuban Peso (192)
        /// </summary>
        [Display(Name = "Cuban Peso")]
        CUP = 192,
        /// <summary>
        /// CVE Cape Verde Escudo (132)
        /// </summary>
        [Display(Name = "Cape Verde Escudo")]
        CVE = 132,
        /// <summary>
        /// CZK Czech Koruna (203)
        /// </summary>
        [Display(Name = "Czech Koruna")]
        CZK = 203,
        /// <summary>
        /// DJF Djiboutian Franc (262)
        /// </summary>
        [Display(Name = "Djiboutian Franc")]
        DJF = 262,
        /// <summary>
        /// DKK Danish Krone (208)
        /// </summary>
        [Display(Name = "Danish Krone")]
        DKK = 208,
        /// <summary>
        /// DOP Dominican Peso (214)
        /// </summary>
        [Display(Name = "Dominican Peso")]
        DOP = 214,
        /// <summary>
        /// DZD Algerian Dinar (012)
        /// </summary>
        [Display(Name = "Algerian Dinar")]
        DZD = 012,
        /// <summary>
        /// EGP Egyptian Pound (818)
        /// </summary>
        [Display(Name = "Egyptian Pound")]
        EGP = 818,
        /// <summary>
        /// ERN Eritrean Nakfa (232)
        /// </summary>
        [Display(Name = "Eritrean Nakfa")]
        ERN = 232,
        /// <summary>
        /// ETB Ethiopian Birr (230)
        /// </summary>
        [Display(Name = "Ethiopian Birr")]
        ETB = 230,
        /// <summary>
        /// EUR Euro (978)
        /// </summary>
        [Display(Name = "Euro")]
        EUR = 978,
        /// <summary>
        /// FJD Fiji Dollar (242)
        /// </summary>
        [Display(Name = "Fiji Dollar")]
        FJD = 242,
        /// <summary>
        /// FKP Falkland Islands Pound (238)
        /// </summary>
        [Display(Name = "Falkland Islands Pound")]
        FKP = 238,
        /// <summary>
        /// GBP Pound Sterling (826)
        /// </summary>
        [Display(Name = "Pound Sterling")]
        GBP = 826,
        /// <summary>
        /// GEL Georgian Lari (981)
        /// </summary>
        [Display(Name = "Georgian Lari")]
        GEL = 981,
        /// <summary>
        /// GHS Ghanaian Cedi (936)
        /// </summary>
        [Display(Name = "Ghanaian Cedi")]
        GHS = 936,
        /// <summary>
        /// GIP Gibraltar Pound (292)
        /// </summary>
        [Display(Name = "Gibraltar Pound")]
        GIP = 292,
        /// <summary>
        /// GMD Gambian Dalasi (270)
        /// </summary>
        [Display(Name = "Gambian Dalasi")]
        GMD = 270,
        /// <summary>
        /// GNF Guinean Franc (324)
        /// </summary>
        [Display(Name = "Guinean Franc")]
        GNF = 324,
        /// <summary>
        /// GTQ Guatemalan Quetzal (320)
        /// </summary>
        [Display(Name = "Guatemalan Quetzal")]
        GTQ = 320,
        /// <summary>
        /// GYD Guyanese Dollar (328)
        /// </summary>
        [Display(Name = "Guyanese Dollar")]
        GYD = 328,
        /// <summary>
        /// HKD Hong Kong Dollar (344)
        /// </summary>
        [Display(Name = "Hong Kong Dollar")]
        HKD = 344,
        /// <summary>
        /// HNL Honduran Lempira (340)
        /// </summary>
        [Display(Name = "Honduran Lempira")]
        HNL = 340,
        /// <summary>
        /// HRK Croatian Kuna (191)
        /// </summary>
        [Display(Name = "Croatian Kuna")]
        HRK = 191,
        /// <summary>
        /// HTG Haitian Gourde (332)
        /// </summary>
        [Display(Name = "Haitian Gourde")]
        HTG = 332,
        /// <summary>
        /// HUF Hungarian Forint (348)
        /// </summary>
        [Display(Name = "Hungarian Forint")]
        HUF = 348,
        /// <summary>
        /// IDR Indonesian Rupiah (360)
        /// </summary>
        [Display(Name = "Indonesian Rupiah")]
        IDR = 360,
        /// <summary>
        /// ILS Israeli New Shekel (376)
        /// </summary>
        [Display(Name = "Israeli New Shekel")]
        ILS = 376,
        /// <summary>
        /// INR Indian Rupee (356)
        /// </summary>
        [Display(Name = "Indian Rupee")]
        INR = 356,
        /// <summary>
        /// IQD Iraqi Dinar (368)
        /// </summary>
        [Display(Name = "Iraqi Dinar")]
        IQD = 368,
        /// <summary>
        /// IRR Iranian Rial (364)
        /// </summary>
        [Display(Name = "Iranian Rial")]
        IRR = 364,
        /// <summary>
        /// ISK Icelandic Króna (352)
        /// </summary>
        [Display(Name = "Icelandic Króna")]
        ISK = 352,
        /// <summary>
        /// JMD Jamaican Dollar (388)
        /// </summary>
        [Display(Name = "Jamaican Dollar")]
        JMD = 388,
        /// <summary>
        /// JOD Jordanian Dinar (400)
        /// </summary>
        [Display(Name = "Jordanian Dinar")]
        JOD = 400,
        /// <summary>
        /// JPY Japanese Yen (392)
        /// </summary>
        [Display(Name = "Japanese Yen")]
        JPY = 392,
        /// <summary>
        /// KES Kenyan Shilling (404)
        /// </summary>
        [Display(Name = "Kenyan Shilling")]
        KES = 404,
        /// <summary>
        /// KGS Kyrgyzstani Som (417)
        /// </summary>
        [Display(Name = "Kyrgyzstani Som")]
        KGS = 417,
        /// <summary>
        /// KHR Cambodian Riel (116)
        /// </summary>
        [Display(Name = "Cambodian Riel")]
        KHR = 116,
        /// <summary>
        /// KMF Comoro Franc (174)
        /// </summary>
        [Display(Name = "Comoro Franc")]
        KMF = 174,
        /// <summary>
        /// KPW North Korean Won (408)
        /// </summary>
        [Display(Name = "North Korean Won")]
        KPW = 408,
        /// <summary>
        /// KRW South Korean Won (410)
        /// </summary>
        [Display(Name = "South Korean Won")]
        KRW = 410,
        /// <summary>
        /// KWD Kuwaiti Dinar (414)
        /// </summary>
        [Display(Name = "Kuwaiti Dinar")]
        KWD = 414,
        /// <summary>
        /// KYD Cayman Islands Dollar (136)
        /// </summary>
        [Display(Name = "Cayman Islands Dollar")]
        KYD = 136,
        /// <summary>
        /// KZT Kazakhstani Tenge (398)
        /// </summary>
        [Display(Name = "Kazakhstani Tenge")]
        KZT = 398,
        /// <summary>
        /// LAK Lao Kip (418)
        /// </summary>
        [Display(Name = "Lao Kip")]
        LAK = 418,
        /// <summary>
        /// LBP Lebanese Pound (422)
        /// </summary>
        [Display(Name = "Lebanese Pound")]
        LBP = 422,
        /// <summary>
        /// LKR Sri Lankan Rupee (144)
        /// </summary>
        [Display(Name = "Sri Lankan Rupee")]
        LKR = 144,
        /// <summary>
        /// LRD Liberian Dollar (430)
        /// </summary>
        [Display(Name = "Liberian Dollar")]
        LRD = 430,
        /// <summary>
        /// LSL Lesotho Loti (426)
        /// </summary>
        [Display(Name = "Lesotho Loti")]
        LSL = 426,
        /// <summary>
        /// LYD Libyan Dinar (434)
        /// </summary>
        [Display(Name = "Libyan Dinar")]
        LYD = 434,
        /// <summary>
        /// MAD Moroccan Dirham (504)
        /// </summary>
        [Display(Name = "Moroccan Dirham")]
        MAD = 504,
        /// <summary>
        /// MDL Moldovan Leu (498)
        /// </summary>
        [Display(Name = "Moldovan Leu")]
        MDL = 498,
        /// <summary>
        /// MGA Malagasy Ariary (969)
        /// </summary>
        [Display(Name = "Malagasy Ariary")]
        MGA = 969,
        /// <summary>
        /// MKD Macedonian Denar (807)
        /// </summary>
        [Display(Name = "Macedonian Denar")]
        MKD = 807,
        /// <summary>
        /// MMK Myanmar Kyat (104)
        /// </summary>
        [Display(Name = "Myanmar Kyat")]
        MMK = 104,
        /// <summary>
        /// MNT Mongolian Tögrög (496)
        /// </summary>
        [Display(Name = "Mongolian Tögrög")]
        MNT = 496,
        /// <summary>
        /// MOP Macanese Pataca (446)
        /// </summary>
        [Display(Name = "Macanese Pataca")]
        MOP = 446,
        /// <summary>
        /// MRO Mauritanian Ouguiya (478)
        /// </summary>
        [Display(Name = "Mauritanian Ouguiya")]
        MRO = 478,
        /// <summary>
        /// MUR Mauritian Rupee (480)
        /// </summary>
        [Display(Name = "Mauritian Rupee")]
        MUR = 480,
        /// <summary>
        /// MVR Maldivian Rufiyaa (462)
        /// </summary>
        [Display(Name = "Maldivian Rufiyaa")]
        MVR = 462,
        /// <summary>
        /// MWK Malawian Kwacha (454)
        /// </summary>
        [Display(Name = "Malawian Kwacha")]
        MWK = 454,
        /// <summary>
        /// MXN Mexican Peso (484)
        /// </summary>
        [Display(Name = "Mexican Peso")]
        MXN = 484,
        /// <summary>
        /// MXV Mexican Unidad De Inversion (979)
        /// </summary>
        [Display(Name = "Mexican Unidad De Inversion")]
        MXV = 979,
        /// <summary>
        /// MYR Malaysian Ringgit (458)
        /// </summary>
        [Display(Name = "Malaysian Ringgit")]
        MYR = 458,
        /// <summary>
        /// MZN Mozambican Metical (943)
        /// </summary>
        [Display(Name = "Mozambican Metical")]
        MZN = 943,
        /// <summary>
        /// NAD Namibian Dollar (516)
        /// </summary>
        [Display(Name = "Namibian Dollar")]
        NAD = 516,
        /// <summary>
        /// NGN Nigerian Naira (566)
        /// </summary>
        [Display(Name = "Nigerian Naira")]
        NGN = 566,
        /// <summary>
        /// NIO Nicaraguan Córdoba (558)
        /// </summary>
        [Display(Name = "Nicaraguan Córdoba")]
        NIO = 558,
        /// <summary>
        /// NOK Norwegian Krone (578)
        /// </summary>
        [Display(Name = "Norwegian Krone")]
        NOK = 578,
        /// <summary>
        /// NPR Nepalese Rupee (524)
        /// </summary>
        [Display(Name = "Nepalese Rupee")]
        NPR = 524,
        /// <summary>
        /// NZD New Zealand Dollar (554)
        /// </summary>
        [Display(Name = "New Zealand Dollar")]
        NZD = 554,
        /// <summary>
        /// OMR Omani Rial (512)
        /// </summary>
        [Display(Name = "Omani Rial")]
        OMR = 512,
        /// <summary>
        /// PAB Panamanian Balboa (590)
        /// </summary>
        [Display(Name = "Panamanian Balboa")]
        PAB = 590,
        /// <summary>
        /// PEN Peruvian Sol (604)
        /// </summary>
        [Display(Name = "Peruvian Sol")]
        PEN = 604,
        /// <summary>
        /// PGK Papua New Guinean Kina (598)
        /// </summary>
        [Display(Name = "Papua New Guinean Kina")]
        PGK = 598,
        /// <summary>
        /// PHP Philippine Peso (608)
        /// </summary>
        [Display(Name = "Philippine Peso")]
        PHP = 608,
        /// <summary>
        /// PKR Pakistani Rupee (586)
        /// </summary>
        [Display(Name = "Pakistani Rupee")]
        PKR = 586,
        /// <summary>
        /// PLN Polish Złoty (985)
        /// </summary>
        [Display(Name = "Polish Złoty")]
        PLN = 985,
        /// <summary>
        /// PYG Paraguayan Guaraní (600)
        /// </summary>
        [Display(Name = "Paraguayan Guaraní")]
        PYG = 600,
        /// <summary>
        /// QAR Qatari Riyal (634)
        /// </summary>
        [Display(Name = "Qatari Riyal")]
        QAR = 634,
        /// <summary>
        /// RON Romanian Leu (946)
        /// </summary>
        [Display(Name = "Romanian Leu")]
        RON = 946,
        /// <summary>
        /// RSD Serbian Dinar (941)
        /// </summary>
        [Display(Name = "Serbian Dinar")]
        RSD = 941,
        /// <summary>
        /// RUB Russian Ruble (643)
        /// </summary>
        [Display(Name = "Russian Ruble")]
        RUB = 643,
        /// <summary>
        /// RWF Rwandan Franc (646)
        /// </summary>
        [Display(Name = "Rwandan Franc")]
        RWF = 646,
        /// <summary>
        /// SAR Saudi Riyal (682)
        /// </summary>
        [Display(Name = "Saudi Riyal")]
        SAR = 682,
        /// <summary>
        /// SBD Solomon Islands Dollar (090)
        /// </summary>
        [Display(Name = "Solomon Islands Dollar")]
        SBD = 090,
        /// <summary>
        /// SCR Seychelles Rupee (690)
        /// </summary>
        [Display(Name = "Seychelles Rupee")]
        SCR = 690,
        /// <summary>
        /// SDG Sudanese Pound (938)
        /// </summary>
        [Display(Name = "Sudanese Pound")]
        SDG = 938,
        /// <summary>
        /// SEK Swedish Krona (752)
        /// </summary>
        [Display(Name = "Swedish Krona")]
        SEK = 752,
        /// <summary>
        /// SGD Singapore Dollar (702)
        /// </summary>
        [Display(Name = "Singapore Dollar")]
        SGD = 702,
        /// <summary>
        /// SHP Saint Helena Pound (654)
        /// </summary>
        [Display(Name = "Saint Helena Pound")]
        SHP = 654,
        /// <summary>
        /// SLL Sierra Leonean Leone (694)
        /// </summary>
        [Display(Name = "Sierra Leonean Leone")]
        SLL = 694,
        /// <summary>
        /// SOS Somali Shilling (706)
        /// </summary>
        [Display(Name = "Somali Shilling")]
        SOS = 706,
        /// <summary>
        /// SRD Surinamese Dollar (968)
        /// </summary>
        [Display(Name = "Surinamese Dollar")]
        SRD = 968,
        /// <summary>
        /// SSP South Sudanese Pound (728)
        /// </summary>
        [Display(Name = "South Sudanese Pound")]
        SSP = 728,
        /// <summary>
        /// STD São Tomé And Príncipe Dobra (678)
        /// </summary>
        [Display(Name = "São Tomé And Príncipe Dobra")]
        STD = 678,
        /// <summary>
        /// SVC Salvadoran Colón (222)
        /// </summary>
        [Display(Name = "Salvadoran Colón")]
        SVC = 222,
        /// <summary>
        /// SYP Syrian Pound (760)
        /// </summary>
        [Display(Name = "Syrian Pound")]
        SYP = 760,
        /// <summary>
        /// SZL Swazi Lilangeni (748)
        /// </summary>
        [Display(Name = "Swazi Lilangeni")]
        SZL = 748,
        /// <summary>
        /// THB Thai Baht (764)
        /// </summary>
        [Display(Name = "Thai Baht")]
        THB = 764,
        /// <summary>
        /// TJS Tajikistani Somoni (972)
        /// </summary>
        [Display(Name = "Tajikistani Somoni")]
        TJS = 972,
        /// <summary>
        /// TMT Turkmenistani Manat (934)
        /// </summary>
        [Display(Name = "Turkmenistani Manat")]
        TMT = 934,
        /// <summary>
        /// TND Tunisian Dinar (788)
        /// </summary>
        [Display(Name = "Tunisian Dinar")]
        TND = 788,
        /// <summary>
        /// TOP Tongan Paʻanga (776)
        /// </summary>
        [Display(Name = "Tongan Paʻanga")]
        TOP = 776,
        /// <summary>
        /// TRY Turkish Lira (949)
        /// </summary>
        [Display(Name = "Turkish Lira")]
        TRY = 949,
        /// <summary>
        /// TTD Trinidad And Tobago Dollar (780)
        /// </summary>
        [Display(Name = "Trinidad And Tobago Dollar")]
        TTD = 780,
        /// <summary>
        /// TWD New Taiwan Dollar (901)
        /// </summary>
        [Display(Name = "New Taiwan Dollar")]
        TWD = 901,
        /// <summary>
        /// TZS Tanzanian Shilling (834)
        /// </summary>
        [Display(Name = "Tanzanian Shilling")]
        TZS = 834,
        /// <summary>
        /// UAH Ukrainian Hryvnia (980)
        /// </summary>
        [Display(Name = "Ukrainian Hryvnia")]
        UAH = 980,
        /// <summary>
        /// UGX Ugandan Shilling (800)
        /// </summary>
        [Display(Name = "Ugandan Shilling")]
        UGX = 800,
        /// <summary>
        /// USD United States Dollar (840)
        /// </summary>
        [Display(Name = "United States Dollar")]
        USD = 840,
        /// <summary>
        /// USN United States Dollar (next Day) (funds Code) (997)
        /// </summary>
        [Display(Name = "United States Dollar (next Day) (funds Code)")]
        USN = 997,
        /// <summary>
        /// UYI Uruguay Peso En Unidades Indexadas (uruiurui) (funds Code) (940)
        /// </summary>
        [Display(Name = "Uruguay Peso En Unidades Indexadas (uruiurui) (funds Code)")]
        UYI = 940,
        /// <summary>
        /// UYU Uruguayan Peso (858)
        /// </summary>
        [Display(Name = "Uruguayan Peso")]
        UYU = 858,
        /// <summary>
        /// UZS Uzbekistan Som (860)
        /// </summary>
        [Display(Name = "Uzbekistan Som")]
        UZS = 860,
        /// <summary>
        /// VEF Venezuelan Bolívar (937)
        /// </summary>
        [Display(Name = "Venezuelan Bolívar")]
        VEF = 937,
        /// <summary>
        /// VND Vietnamese Đồng (704)
        /// </summary>
        [Display(Name = "Vietnamese Đồng")]
        VND = 704,
        /// <summary>
        /// VUV Vanuatu Vatu (548)
        /// </summary>
        [Display(Name = "Vanuatu Vatu")]
        VUV = 548,
        /// <summary>
        /// WST Samoan Tala (882)
        /// </summary>
        [Display(Name = "Samoan Tala")]
        WST = 882,
        /// <summary>
        /// XAF Cfa Franc Beac (950)
        /// </summary>
        [Display(Name = "Cfa Franc Beac")]
        XAF = 950,
        /// <summary>
        /// XAG Silver (961)
        /// </summary>
        [Display(Name = "Silver")]
        XAG = 961,
        /// <summary>
        /// XAU Gold (959)
        /// </summary>
        [Display(Name = "Gold")]
        XAU = 959,
        /// <summary>
        /// XBA European Composite Unit (955)
        /// </summary>
        [Display(Name = "European Composite Unit")]
        XBA = 955,
        /// <summary>
        /// XBB European Monetary Unit (956)
        /// </summary>
        [Display(Name = "European Monetary Unit")]
        XBB = 956,
        /// <summary>
        /// XBC European Unit Of Account 9 (957)
        /// </summary>
        [Display(Name = "European Unit Of Account 9")]
        XBC = 957,
        /// <summary>
        /// XBD European Unit Of Account 17 (958)
        /// </summary>
        [Display(Name = "European Unit Of Account 17")]
        XBD = 958,
        /// <summary>
        /// XCD East Caribbean Dollar (951)
        /// </summary>
        [Display(Name = "East Caribbean Dollar")]
        XCD = 951,
        /// <summary>
        /// XDR Special Drawing Rights (960)
        /// </summary>
        [Display(Name = "Special Drawing Rights")]
        XDR = 960,
        /// <summary>
        /// XOF Cfa Franc Bceao (952)
        /// </summary>
        [Display(Name = "Cfa Franc Bceao")]
        XOF = 952,
        /// <summary>
        /// XPD Palladium (964)
        /// </summary>
        [Display(Name = "Palladium")]
        XPD = 964,
        /// <summary>
        /// XPF Cfp Franc (953)
        /// </summary>
        [Display(Name = "Cfp Franc")]
        XPF = 953,
        /// <summary>
        /// XPT Platinum (962)
        /// </summary>
        [Display(Name = "Platinum")]
        XPT = 962,
        /// <summary>
        /// XSU Sucre (994)
        /// </summary>
        [Display(Name = "Sucre")]
        XSU = 994,
        /// <summary>
        /// XTS Code Reserved For Testing Purposes (963)
        /// </summary>
        [Display(Name = "Code Reserved For Testing Purposes")]
        XTS = 963,
        /// <summary>
        /// XUA Adb Unit Of Account (965)
        /// </summary>
        [Display(Name = "Adb Unit Of Account")]
        XUA = 965,
        /// <summary>
        /// XXX No Currency  (999)
        /// </summary>
        [Display(Name = "No Currency ")]
        XXX = 999,
        /// <summary>
        /// YER Yemeni Rial (886)
        /// </summary>
        [Display(Name = "Yemeni Rial")]
        YER = 886,
        /// <summary>
        /// ZAR South African Rand (710)
        /// </summary>
        [Display(Name = "South African Rand")]
        ZAR = 710,
        /// <summary>
        /// ZMW Zambian Kwacha (967)
        /// </summary>
        [Display(Name = "Zambian Kwacha")]
        ZMW = 967,
        /// <summary>
        /// ZWL Zimbabwean Dollar (932)
        /// </summary>
        [Display(Name = "Zimbabwean Dollar")]
        ZWL = 932,
    }
}
